import p1 from "../../assets/images/productsimg/photo_2019-12-11_16-39-53.jpg";

const productsbags = [
  {
    id: 1,
    category: "کیف_چرمی",
    parent1: "کیف_مجلسی_زنانه",
    parent: 1,
    name: "کیف مجلسی زنانه کد100",
    slug: "کیف_مجلسی_زنانه_کد_100",
    price: "1500000",
    off: "15%",
    priceoff: "1200000",
    count: "5",
    material: "چرم گاوی",
    length: "25cm",
    height: "28cm",
    width: "10cm",
    insertdate: "1402/04/01",
    attributes: [
      { id: "1", color: "قرمز", colorcount: "3", img: p1 },
      { id: "2", color: "مشکی", colorcount: "2", img: p1 },
    ],
  },

  {
    id: 2,
    category: "کیف های چرمی",
    parent: "کیف_دوشی_زنانه",
    name: "کیف دوشی زنانه کد200",
    slug: "کیف_دوشی_زنانه_کد200",
    price: "1800000",
    off: "10%",
    priceoff: "1000000",
    count: "4",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "مشکی" },
      { title: "جنس", value: "چرم شتر" },
      { title: "طول", value: "27cm" },
      { title: "ارتفاع", value: "26cm" },
      { title: "عرض", value: "11cm" },
    ],
  },
  {
    id: 3,
    category: "کیف های چرمی",
    parent: "کیف_مجلسی_زنانه",
    name: " کیف مجلسی زنانه کد101",
    slug: "کیف_مجلسی_زنانه_کد_101",
    price: "800000",
    off: "5%",
    priceoff: "700000",
    count: "8",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "قرمز" },
      { title: "جنس", value: "چرم گاوی" },
      { title: "طول", value: "25cm" },
      { title: "ارتفاع", value: "28cm" },
      { title: "عرض", value: "10cm" },
    ],
  },

  {
    id: 4,
    category: "کیف های چرمی",
    parent: "کیف_پول_کتی",
    name: "کیف پول کتی کد300",
    slug: "کیف_پول_کتی_کد_300",
    price: "900000",
    off: "7%",
    priceoff: "700000",
    count: "6",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "سبز" },
      { title: "جنس", value: "چرم شتر" },
      { title: "طول", value: "10cm" },
      { title: "عرض", value: "10cm" },
    ],
  },

  {
    id: 5,
    category: "اکسسوری_چرمی",
    parent: "کمربند_چرمی",
    name: " کمربند چرمی کد400",
    slug: "کمربند_چرمی_کد",
    size: "120cm",
    price: "1500000",
    off: "15%",
    priceoff: "1200000",
    count: "8",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "قهوه ای" },
      { title: "جنس", value: "چرم گاوی" },
      { title: "طول", value: "25cm" },
      { title: "عرض", value: "10cm" },
    ],
  },

  {
    id: 6,
    category: "اکسسوری چرمی",
    parent: "قاب_گوشی_موبایل",
    name: "قاب گوشی موبایل کد500",
    slug: "قاب_گوشی_موبایل_کد_500",
    price: "500000",
    off: "10%",
    priceoff: "400000",
    count: "8",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "سبز" },
      { title: "جنس", value: "چرم شترمرغ" },
      { title: "طول", value: "12cm" },
      { title: "عرض", value: "7cm" },
    ],
  },

  {
    id: 7,
    category: "کفش چرمی",
    parent: "کفش_زنانه",
    name: "صندل زنانه کد600",
    slug: "کفش_زنانه_کد_600",
    size: "38",
    price: "700000",
    off: "20%",
    priceoff: "500000",
    count: "0",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "سبز" },
      { title: "جنس", value: "چرم شتر" },
      { title: "طول", value: "10cm" },
      { title: "عرض", value: "10cm" },
    ],
  },
  {
    id: 8,
    category: "پوشاک چرمی",
    parent: "کلاه_چرمی",
    name: "کلاه چرمی کد700",
    slug: "کلاه_چرمی_کد_700",
    size: "xl",
    price: "300000",
    off: "15%",
    priceoff: "200000",
    count: "0",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "سبز" },
      { title: "جنس", value: "چرم شتر" },
      { title: "طول", value: "10cm" },
      { title: "عرض", value: "10cm" },
    ],
  },

  {
    id: 9,
    category: "دکوراسیون و منزل",
    parent: "کوسن_چرمی",
    name: "کوسن چرمی کد800",
    slug: "کوسن_چرمی_کد_800",
    price: "400000",
    off: "25%",
    priceoff: "300000",
    count: "1",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "سبز" },
      { title: "جنس", value: "چرم شترمرغ" },
      { title: "طول", value: "12cm" },
      { title: "عرض", value: "7cm" },
    ],
  },

  {
    id: 10,
    category: "محصولات بچگانه",
    parent: "کوله_پشتی_بچگانه",
    name: "کوله پشتی بچگانه کد900",
    slug: "کوله_پشتی_بچگانه_کد_900",
    price: "900000",
    off: "15%",
    priceoff: "800000",
    count: "3",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "سبز" },
      { title: "جنس", value: "چرم شترمرغ" },
      { title: "طول", value: "12cm" },
      { title: "عرض", value: "7cm" },
    ],
  },
  {
    id: 11,
    category: "چرم",
    parent: "چرم_گاوی",
    name: "چرم گاوی فلوتر کد1000",
    slug: "چرم_گاوی_فلوتر_کد1000",
    size: "6foot",
    price: "60000",
    off: "15%",
    priceoff: "45000",
    count: "2",
    material: "چرم گاوی",
    img: p1,
    attributes: [
      { title: "رنگ", value: "سبز" },
      { title: "جنس", value: "چرم شترمرغ" },
      { title: "طول", value: "12cm" },
      { title: "عرض", value: "7cm" },
    ],
  },
];

export default productsbags;
